
name: 'Upload Coverage'

on: [pull_request, push, workflow_dispatch]

jobs:
  upload:
    name: 'Upload Coverage'
    runs-on: ubuntu-latest
    steps:
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }